language: node_js

node_js: "stable"

install: npm install

services: postgresql 
 
before_script: psql -c 'create database testing;' -U ricah -p kigali

script: npm test

after_script: npm run coveralls